# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./

    steps:
    - name: deploying to prod via ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{ secrets.STAGING_SSH_HOST }}
        username: ${{ secrets.STAGING_SSH_USERNAME }}
        password: ${{ secrets.STAGING_SSH_PASSWORD }}
        port: 22
        command: bash /var/www/wedding.mykeels.com/scripts/deploy.sh
